import { useRoute, useLocation } from "wouter";
import { tasks } from "@/lib/data";
import { Layout } from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { CheckCircle2, AlertTriangle, Download, Home } from "lucide-react";
import { ConfidenceMeter } from "@/components/ConfidenceMeter";

export default function Summary() {
  const [match, params] = useRoute("/task/:id/summary");
  const [, setLocation] = useLocation();

  if (!match || !params) return null;

  const task = tasks.find(t => t.id === params.id);
  if (!task) {
    setLocation("/404");
    return null;
  }

  // Mock score for demonstration - in a real app this would be calculated from state
  const mockScore = 85;

  const handleDownload = () => {
    const content = `
DIGITAL CONFIDENCE COACH - TASK REPORT
----------------------------------------
Task: ${task.title}
Date: ${new Date().toLocaleDateString()}
Status: Completed

SUMMARY
You have successfully completed the guided flow for "${task.title}".
Based on your inputs, we have analyzed the safety of your actions.

KEY SAFETY NOTES
- Always verify the URL matches the official vendor exactly.
- If a file extension looks wrong (e.g., .exe for a document), delete it immediately.
- Keep your system updated to protect against known vulnerabilities.

NEXT STEPS
1. If you installed software, check for a "Custom Install" option to avoid bloatware.
2. Run a quick scan with your antivirus if you feel uncertain.
3. Monitor your system for any unexpected behavior in the next 24 hours.

----------------------------------------
Generated by Digital Confidence Coach
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `DCC-Report-${task.id}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Layout>
      <div className="max-w-3xl mx-auto">
        <div className="border border-border bg-card p-12 space-y-12">
          {/* Header */}
          <div className="text-center space-y-6">
            <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-success/10 text-success mb-4">
              <CheckCircle2 size={48} strokeWidth={1.5} />
            </div>
            <h1 className="text-4xl font-bold uppercase tracking-tight">
              Flow Completed
            </h1>
            <p className="text-xl text-muted-foreground">
              You have finished the guidance for <span className="text-foreground font-medium">{task.title}</span>.
            </p>
          </div>

          {/* Analysis */}
          <div className="space-y-8 border-y border-border py-8">
            <ConfidenceMeter score={mockScore} className="max-w-md mx-auto" />
            
            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-widest text-primary">
                  Actions Taken
                </h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  {task.steps.map((step, i) => (
                    <li key={step.id} className="flex items-start gap-2">
                      <span className="font-mono text-xs text-border mt-1">{(i + 1).toString().padStart(2, '0')}</span>
                      <span>{step.title}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-widest text-warning">
                  Watch Out For
                </h3>
                <ul className="space-y-3 text-sm text-muted-foreground">
                  <li className="flex gap-2">
                    <AlertTriangle size={16} className="text-warning shrink-0" />
                    <span>Unexpected pop-ups asking for admin rights.</span>
                  </li>
                  <li className="flex gap-2">
                    <AlertTriangle size={16} className="text-warning shrink-0" />
                    <span>Browser homepage or search engine changes.</span>
                  </li>
                  <li className="flex gap-2">
                    <AlertTriangle size={16} className="text-warning shrink-0" />
                    <span>Computer running unusually slow or hot.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              onClick={handleDownload}
              variant="outline"
              className="rounded-none border-primary text-primary hover:bg-primary hover:text-primary-foreground h-12 px-8 uppercase tracking-wide font-bold"
            >
              <Download className="mr-2 h-4 w-4" /> Download Report
            </Button>
            <Button 
              onClick={() => setLocation("/")}
              className="rounded-none bg-foreground text-background hover:bg-foreground/90 h-12 px-8 uppercase tracking-wide font-bold"
            >
              <Home className="mr-2 h-4 w-4" /> Return Home
            </Button>
          </div>
        </div>
      </div>
    </Layout>
  );
}
